### PR TITLE
Frontend changes lying on my github

### PR DESCRIPTION
**Pull request by yashsriv**
These are the changes currently running on the frontend at https://search.pclub.in

They weren't pushed to pclubiitk/master, and need to be merged.

@adarshaj we have decided that all commits to pclub github should undergo strict quality checks. If you could please review this.

### CODE REVIEW

**Comment by shivanshuag** [comment]
Why is this website accessible outside IITK?

**Comment by yashsriv** [comment]
@sakshamsharma 's decision. Still being debated with @kunalapila

**Comment by pallavagarwal07** [comment]
@shivanshuag It was decided that photos will only be made visible from inside IITK, however there didn't seem to be any argument against showing the general database to outside IITK.

On second thoughts though, hiding information like blood group, hometown could be considered.

**Comment by yashsriv** [comment]
Rebasing and merging due to inactivity.

**Pull request merged**
