### PR TITLE
Upgrade to Angular 6

### PR DESCRIPTION
**Pull request by abdatta**
This PR addresses #31 and updates Angular to version 6.x along with other dependencies as per compatibility requirements.

The following is a non-exhaustive list of steps taken:

- Updated all angular packages to 6.x as per https://update.angular.io/?l=2&v=5.0-6.1
- Updated non-compatible packages (like `ngx-clipboard` and `ngx-infinite-scroll`) to compatible versions.
- Checked for any breaking changes from changelogs of these packages, and updated the code where required.
- Updated all rxjs code to use 6.x syntax to get better typescript support for them (and other advantages of rxjs 6).
- Compiled and built the entire frontend and tested it manually in browser.
- Removed use of yarn since `package-lock.json` now takes care of exact dependencies.
- Updated all scripts, including Dockerfiles and CI files, to use npm instead of yarn.
- Also updated the dockerfile to use `node12-alpine` image instead of `node6-alpine`, to support building angular 6 projects.
- Tested the dockerfile changes by building a docker image in local.

Steps not checked:
- Service worker and PWA support couldn't be thoroughly tested as I did not have an https domain to try them out. But it is likely to work fine. Lemme know if there are other ways to test them.

Future possible steps that can be taken (as separate PRs):
- Upgrade Angular to 7, 8, 9 and finally 10. If anyone is interested to do it, please mention me, else I'll do them sometime.
- (Optional) Use @angular/service-worker and angular's PWA support instead of the custom service worker.

### CODE REVIEW

**Comment by abdatta** [comment]
Please review @yashsriv

**Comment by dryairship** [comment]
For testing stuff that requires an https domain, you can try out [ngrok](https://ngrok.com/).

**Comment by yashsriv** [comment]
lgtm. @dryairship can you test it out properly via Forticlient VPN / deploying the dockerfile and then accept.

**Comment by dryairship** [comment]
Works fine.

**Review by dryairship — APPROVED** [review]

**Comment by abdatta** [comment]
> For testing stuff that requires an https domain, you can use [ngrok](https://ngrok.com/).

Oh, good idea! Completely forgot that ngrok supports https as well! Thanks!

**Pull request merged**
