### PR TITLE
Fix Detail Component Max Height

### PR DESCRIPTION
**Pull request by abdatta**
The details dialog showed an unnecessary scrollbar on some screens.
image
It's a very basic issue, but it kept bothering me :stuck_out_tongue:. Fixed it.

### CODE REVIEW

**Comment by abdatta** [comment]
Also added the functionality for the close button on the search bar. Issue #21 .

**Comment by yashsriv** [comment]
I believe adding `max-height: 80vh` to `.centered-dialog` in frontend/src/styles.css would have the same effect??

**Comment by abdatta** [comment]
Let me check and if it works for `.centered-dialog` I'll commit the edit.

**Comment by abdatta** [comment]
Nope. It doesn't work for `.centered-dialog` or `.centered-dialog .mat-dialog-container` in the frontend/src/styles.css . I've checked both. Btw, is there any issue with `detail.component.css`?

**Comment by yashsriv** [comment]
@abdatta  Could you please check if this issue is still present on current master code?

**Comment by abdatta** [comment]
Yes, it still prevails.

**Comment by abdatta** [comment]
@yashsriv Also, I have fixed the merge conflicts now. You can review and merge the PR anytime.

**Comment by yashsriv** [comment]
Merged via #24

**Pull request closed without merging**
